/* Plugin Template generated by Pawn Studio */

#include <sourcemod>

public Plugin:myinfo = 
{
	name = "Source Addon",
	author = "=[JFF]=Thunder",
	description = "JustForFun Addon",
	version = "1.0.0",
	url = "http://justforfun-gaming.com"
}

public OnPluginStart()
{
	Database db = SQL_DefConnect(error, sizeof(error));
}
